apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus_m1:9090 
  isDefault: true
  access: proxy
  editable: true
  
- name: InfluxDB_v2_Flux
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  jsonData:
    version: Flux
    organization: ${DOCKER_INFLUXDB_INIT_ORG}
    defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
    tlsSkipVerify: true
  secureJsonData:
    token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}